'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import { AnimatePresence } from 'framer-motion'
import Nav from './components/Nav/Nav.jsx'



const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children}) {
 

  return (
    <AnimatePresence mode="wait">
      
    <html lang="en">
      <body className={inter.className}>
        <header>
        <div className=' top-0 left-0 w-full border-1 border-black'>
      <Nav></Nav>
      </div>
        </header>
        
        <main>
            <section >{children}</section>
          </main>
      
      </body>

      
    </html>
    </AnimatePresence>
  )
}
